<?php

namespace Application\Utilities;

//setlocale( LC_ALL, "en_US.UTF8" );

function slugify( $str, $char = "-", $tf = "lowercase" ) {
    $str = iconv( "utf-8", "us-ascii//translit//ignore", $str ); // transliterate
    $str = str_replace( "'", "", $str ); // remove “'” generated by iconv
    $str = preg_replace( "~[^a-z0-9]+~ui", $char, $str ); // replace unwanted by single “-”
    $str = trim( $str, $char ); // trim “-”
    
    if( $tf == "lowercase" ) 
        $str = mb_strtolower( $str, "utf-8" ); // lowercase
    elseif( $tf == "uppercase" ) 
        $str = mb_strtoupper( $str, "utf-8" );
    
    return $str;
}

?>